version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: silatorjana_app:latest
    container_name: silatorjana_app
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: silatorjana_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
